version: "3.8"

services:
  postgres:
      image: postgres
      container_name: postgres
      volumes:
        - type: volume
          source: POSTGRES_DATA
          target: /var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: keycloak
        KEYCLOAK_PASSWORD: keycloak
      ports:
        - 8080:8080
      depends_on:
        - postgres

volumes:
  POSTGRES_DATA:
    name: POSTGRES_DATA
    driver: local