version: "3.8"

services:
  vault:
    image: hashicorp/vault:latest
    restart: always
    volumes:
      - type: volume
        source: VAULT_DATA
        target: /vault/data
      - type: volume
        source: VAULT_LOG
        target: /etc/vault/logs
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: "vault server -dev"
    
volumes:
  VAULT_DATA:
    name: VAULT_DATA
  VAULT_LOG:
    name: VAULT_LOG
